motd file=/etc/motd
syslog facility=daemon

[gentoo-portage]
comment = Gentoo Linux, Portage tree mirror
path = /srv/ftp/gentoo-portage
exclude = distfiles
read only = true
uid = ftp
gid = ftp

[blackarch]
comment = BlackArch Linux, download and Pacman repositories mirror
path = /srv/ftp/blackarch
read only = true
uid = ftp
gid = ftp

[tails]
comment = Tails, the amnesic incognito live system mirror
path = /srv/ftp/tails
read only = true
uid = ftp
gid = ftp

[archstrike]
comment = ArchStrike, security-focused Arch Linux derivative mirror
path = /srv/ftp/archstrike
read only = true
uid = ftp
gid = ftp

[ctan]
comment = CTAN, the Comprehensive TeX Archive Network mirror
path = /srv/ftp/ctan
read only = true
uid = ftp
gid = ftp

[gnu]
comment = GNU Project software mirror (ftp.gnu.org)
path = /srv/ftp/gnu
read only = true
uid = ftp
gid = ftp

[slackware]
comment = Slackware Linux mirror
path = /srv/ftp/slackware
read only = true
uid = ftp
gid = ftp
