motd file=/etc/motd
syslog facility=daemon

[gentoo-portage]
comment = Gentoo Linux, Portage tree mirror
path = /srv/ftp/gentoo-portage
exclude = distfiles
read only = true
uid = ftp
gid = ftp

[blackarch]
comment = BlackArch Linux, download and Pacman repositories mirror
path = /srv/ftp/blackarch
read only = true
uid = ftp
gid = ftp

[tails]
comment = Tails, the amnesic incognito live system mirror
path = /srv/ftp/tails
read only = true
uid = ftp
gid = ftp
