#!/bin/bash

(

# Wait for lock on $0.lock (fd 200) for 10 seconds
/usr/bin/flock -x -w 10 200 || exit 1

RSYNC="/usr/bin/rsync"
OPTS="--quiet --recursive --links --perms --times -D --delete --timeout=300"

SRC1="rsync://blackarch.org/blackarch/"
SRC2="rsync://knuth.mirrortr.com/blackarch/"
SRC3="rsync://blackarch.cdndepo.com/"
SRC4="rsync://blackarch.mirror.packetfire.org/"
SRC5="rsync://mirror.team-cymru.org/blackarch/"
SRC6="rsync://mirror.jmu.edu/blackarch/"
SRC7="rsync://mirror.oss.maxcdn.com/mirrors/blackarch/"

DST="/srv/ftp/blackarch/"

echo "Started update at" `date` >> $0.log 2>&1
/usr/bin/logger -t sync-ba "Re-rsyncing the blackarch tree"
${RSYNC} ${OPTS} ${SRC1} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC2} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC3} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC4} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC5} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC6} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC7} ${DST} >> $0.log 2>&1

echo "End: "`date` >> $0.log 2>&1

) 200>$0.lock
