#!/bin/bash

(

# Wait for lock on $0.lock (fd 200) for 10 seconds
/usr/bin/flock -x -w 10 200 || exit 1

RSYNC="/usr/bin/rsync"
OPTS="--quiet --recursive --links --perms --times -D --delete --timeout=300"

SRC1="rsync://masterportage.gentoo.org/gentoo-portage"
SRC2="rsync://rsync.ch.gentoo.org/gentoo-portage"
SRC3="rsync://rsync.de.gentoo.org/gentoo-portage"
SRC4="rsync://rsync.us.org/gentoo-portage"

DST="/srv/ftp/gentoo-portage/"

echo "Started update at" `date` >> $0.log 2>&1
/usr/bin/logger -t sync-gp "Re-rsyncing the gentoo-portage tree"
${RSYNC} ${OPTS} ${SRC1} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC2} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC3} ${DST} >> $0.log 2>&1 || \
${RSYNC} ${OPTS} ${SRC4} ${DST} >> $0.log 2>&1

echo "End: "`date` >> $0.log 2>&1

) 200>$0.lock
